name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: python -m build

      - name: Upload artifact for publishing
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dists
          path: dist/

  pypi-publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs: build

    environment: pypi-publish

    permissions:
      id-token: write

    steps:
      - name: Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-dists
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
